apiVersion: v1
kind: Service
metadata:
  name: backend-python
  labels:
    app: backend-python
    app.kubernetes.io/part-of: microservices-app
spec:
  selector:
    app: backend-python
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 8001
    targetPort: metrics
    name: metrics