apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
spec:
  template:
    spec:
      containers:
      - name: backend-python
        env:
        - name: PYTHON_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        - name: ENABLE_METRICS
          value: "true"