apiVersion: v1
kind: Service
metadata:
  name: backend-node
  labels:
    app: backend-node
    app.kubernetes.io/part-of: microservices-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: metrics
    port: 3001
    targetPort: 3001
  selector:
    app: backend-node