apiVersion: v1
kind: Service
metadata:
  name: backend-node
  labels:
    app: backend-node
    app.kubernetes.io/part-of: microservices-app
spec:
  selector:
    app: backend-node
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 3001
    targetPort: metrics
    name: metrics