apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu-usuario/tu-repositorio-gitops.git
    targetRevision: HEAD
    path: apps/backend-python/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true