apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
spec:
  template:
    spec:
      containers:
      - name: backend-node
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"