apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- config-patch.yaml

images:
- name: ${YOUR_REGISTRY}/backend-node
  newName: ${YOUR_REGISTRY}/backend-node
  newTag: latest