apiVersion: v1
kind: Service
metadata:
  name: backend-java
  labels:
    app: backend-java
    app.kubernetes.io/part-of: microservices-app
spec:
  selector:
    app: backend-java
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 8081
    targetPort: metrics
    name: metrics